spring:
    datasource:
      name: test
      url: jdbc:mysql://120.78.74.194:3306/hyskjf?characterEncoding=utf8&useSSL=false
      username: root
      password: Root1234_

mybatis:
#Mybatis扫描
    mapper-locations: classpath*:mapper/*.xml
#起别名。可省略写mybatis的xml中的resultType的全路径
    type-aliases-package: com.scau.hyskjf.pojo